services:
  backend-service:
    # Image and platform settings
    image: lkduy2602/nestjs-deploy-test:latest
    platform: linux/amd64
    pull_policy: always

    # Container identity
    container_name: ${SERVICE_NAME:-nestjs-deploy-test}

    # Environment variables
    env_file:
      - .env

    # Runtime behavior
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${PORT}/ping']
      interval: 30s
      timeout: 10s
      retries: 3
