version: '3'

services:
  nestjs-deploy-test:
    platform: linux/amd64
    image: lkduy2602/nestjs-deploy-test:latest
    pull_policy: always
    env_file:
      - .env
    restart: always
    ports:
      - ${PORT}:${PORT}
