services:
  backend-service:
    # Image and platform settings
    image: lkduy2602/nestjs-deploy-test:latest
    platform: linux/amd64
    pull_policy: always

    # Container identity
    container_name: ${SERVICE_NAME}

    # Environment variables
    env_file:
      - .env

    # Health monitoring and recovery
    restart: always
    # healthcheck:
    #   test: 'curl -f http://localhost:8080/ping'
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
