name: Deploy development

on:
  push:
    branches: 'main'

jobs:
  deploy:
    uses: lkduy2602/infrastructure-configs/.github/workflows/reusable-build-deploy.yml@main
    with:
      service_name: 'nestjs-deploy-test'
      environment: 'dev'
